version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=autonest_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      sh -c "python manage.py migrate --settings=autonest_core.settings.prod &&
             gunicorn --bind 0.0.0.0:8000 autonest_core.wsgi:application"
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-z-1k*u-c^g7_@wm12p1kzi)e49l=t+70niwkl_c2d#!lbn%ujz
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DB_NAME=autonest_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1
      - SOCIAL_AUTH_GOOGLE_CLIENT_ID=994976901936-675iqc8cm4pnc1ihgishq4daclg9kbpi.apps.googleusercontent.com
      - SOCIAL_AUTH_GOOGLE_SECRET=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
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
  media_volume: