# Generated by Django 5.2.1 on 2025-05-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='year',
            new_name='model_year',
        ),
    ]
